AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudNap - One-click setup for EC2 lifecycle management (cloudnap.in)'

Parameters:
  ExternalId:
    Type: String
    Description: Your unique External ID from CloudNap (found on the setup page)
    MinLength: 1
    ConstraintDescription: External ID cannot be empty. Copy it from your CloudNap setup page.

Resources:
  CloudNapPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: CloudNapPolicy
      Description: Grants CloudNap permission to manage EC2 instances
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: CloudNapControl
            Effect: Allow
            Action:
              - ec2:DescribeInstances
              - ec2:DescribeVpcs
              - ec2:DescribeInstanceStatus
              - ec2:StartInstances
              - ec2:StopInstances
              - ec2:DescribeTags
              - ec2:DescribeVolumes
            Resource: '*'

  CloudNapRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloudnap-user
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::758026825879:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      ManagedPolicyArns:
        - !Ref CloudNapPolicy

Outputs:
  RoleARN:
    Description: Copy this Role ARN and paste it in CloudNap
    Value: !GetAtt CloudNapRole.Arn
  RoleName:
    Description: IAM Role name created for CloudNap
    Value: !Ref CloudNapRole


# https://cloudnap-stack.s3.us-east-1.amazonaws.com/cloudnap-stack.yaml?response-content-disposition=inline&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEAYaCXVzLWVhc3QtMSJGMEQCIFpbuUk9UCxVWMo01xHr52uhFS%2B04WJXn2tuczREEWmZAiBfcUY2pJ8wQx7NCpMVPeg7dF9PnJC6kTpt4IQOTQVBySrCAwjP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAAaDDcxMTM4NzEyNjE3NSIMpV9G64xQy6kqgsy%2BKpYDhD0JEqLSr9VVMX0z8bl7YAQZfvWfUUPvx%2B9109jno0rtb8BwK9c%2FzBVjYVPhJfxguv%2B2ADVuSFzCCj3cMkSd%2Bp2pG%2FzAbnDMR10Vj54lc2jKdRJDRYK3oubQhsgo85%2BWfHfUM0fYZsyHEZrDdRTCeYchNeViMFxFV8H1f7CR%2BZPbS0FrWDbkQIPqAF6AAdmJQKbUF6uWO25KkdLh8riERmY%2FWtPTmTqPCLLyBze8Zu8G%2FP5ZIdVnANJenhRPitrdyu8oVWf9r9KQmCMXbq9qWXLJS7tfZn1yskzq2GhDnjppI89iLtJNJ9lhnTW8N1dq8F%2Bq4rWaMR6sLy3PkJiyUFLQgYtNPZxAp3g7QfOHDYYzI0tNr3x69V0RA4S%2FJSOcgyz8ZlIDebkDsgaAfJ0%2Ba0PjVDQlCa0PYSLL1fuvw%2BAgagwnaGbYr%2FSQ6D0jN%2FeMbcQUWyKYxeJf1cAB7JTVeKsIV9rlDFJ9voYX5Jqitt1NRB3ifk74Gpd8nGv5O0kJazNmu63Fs1OM74QB3Gci6WZeMMXyKjDcjYfPBjrfAkGKxz35t9k5KOzx7wZrt9xGKRXt9BswOaHLTpcIHVkfwyD7WXR3AfTtmiddUXgJwzBSD8NkuS%2F0yajMwwRwfGlrvduWy4sdIqX%2B2mlEYWkVrbYb%2BfBWewqzgQ62MoVCUhKG%2BeUYTslRh3yebrZfSQB2gGRvUIAaYtC%2BehNuKojas7GVdUIgiVoPiimwvDk%2BoIo9Nr3MmDKzE7926nehZlxlzp5mNL6KoUrdWv6o2I7QQo8Z82OOAeEmybBCTqZrMAWUoRqF3Esi7GGP6%2BA%2B9D8GwLOphOuGlj17tVkhkSHpiBQGad8N7bihUR50B3XQUunlEejjterNG4c9rrrA3YQDv%2F2k%2BWzOl%2BTuwAqc2M9cJMJz3bQESFJxKB%2FXU83QH7jV%2FRusQuMGzvL2S3YjvFQJWkx9lOrnSMuofoX%2FjCmuVN5E%2BYIreezL2VZpQn9pigEFsb5AcFPav8sKNJCfHA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIA2LIP2DGP5GIWTOE5%2F20260417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260417T054333Z&X-Amz-Expires=43200&X-Amz-SignedHeaders=host&X-Amz-Signature=6e351df7aa58a26fa112b84ce5e70d39429de551ea3dbbc62b0c9e6c1f2de0f3



https://console.aws.amazon.com/cloudformation/home#/stacks/quickcreate
  ?templateURL=https://cloudnap-stack.s3.us-east-1.amazonaws.com/cloudnap-stack.yaml?response-content-disposition=inline&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Security-Token=IQoJb3JpZ2luX2VjEAYaCXVzLWVhc3QtMSJGMEQCIFpbuUk9UCxVWMo01xHr52uhFS%2B04WJXn2tuczREEWmZAiBfcUY2pJ8wQx7NCpMVPeg7dF9PnJC6kTpt4IQOTQVBySrCAwjP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2F8BEAAaDDcxMTM4NzEyNjE3NSIMpV9G64xQy6kqgsy%2BKpYDhD0JEqLSr9VVMX0z8bl7YAQZfvWfUUPvx%2B9109jno0rtb8BwK9c%2FzBVjYVPhJfxguv%2B2ADVuSFzCCj3cMkSd%2Bp2pG%2FzAbnDMR10Vj54lc2jKdRJDRYK3oubQhsgo85%2BWfHfUM0fYZsyHEZrDdRTCeYchNeViMFxFV8H1f7CR%2BZPbS0FrWDbkQIPqAF6AAdmJQKbUF6uWO25KkdLh8riERmY%2FWtPTmTqPCLLyBze8Zu8G%2FP5ZIdVnANJenhRPitrdyu8oVWf9r9KQmCMXbq9qWXLJS7tfZn1yskzq2GhDnjppI89iLtJNJ9lhnTW8N1dq8F%2Bq4rWaMR6sLy3PkJiyUFLQgYtNPZxAp3g7QfOHDYYzI0tNr3x69V0RA4S%2FJSOcgyz8ZlIDebkDsgaAfJ0%2Ba0PjVDQlCa0PYSLL1fuvw%2BAgagwnaGbYr%2FSQ6D0jN%2FeMbcQUWyKYxeJf1cAB7JTVeKsIV9rlDFJ9voYX5Jqitt1NRB3ifk74Gpd8nGv5O0kJazNmu63Fs1OM74QB3Gci6WZeMMXyKjDcjYfPBjrfAkGKxz35t9k5KOzx7wZrt9xGKRXt9BswOaHLTpcIHVkfwyD7WXR3AfTtmiddUXgJwzBSD8NkuS%2F0yajMwwRwfGlrvduWy4sdIqX%2B2mlEYWkVrbYb%2BfBWewqzgQ62MoVCUhKG%2BeUYTslRh3yebrZfSQB2gGRvUIAaYtC%2BehNuKojas7GVdUIgiVoPiimwvDk%2BoIo9Nr3MmDKzE7926nehZlxlzp5mNL6KoUrdWv6o2I7QQo8Z82OOAeEmybBCTqZrMAWUoRqF3Esi7GGP6%2BA%2B9D8GwLOphOuGlj17tVkhkSHpiBQGad8N7bihUR50B3XQUunlEejjterNG4c9rrrA3YQDv%2F2k%2BWzOl%2BTuwAqc2M9cJMJz3bQESFJxKB%2FXU83QH7jV%2FRusQuMGzvL2S3YjvFQJWkx9lOrnSMuofoX%2FjCmuVN5E%2BYIreezL2VZpQn9pigEFsb5AcFPav8sKNJCfHA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIA2LIP2DGP5GIWTOE5%2F20260417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260417T054333Z&X-Amz-Expires=43200&X-Amz-SignedHeaders=host&X-Amz-Signature=6e351df7aa58a26fa112b84ce5e70d39429de551ea3dbbc62b0c9e6c1f2de0f3
  &stackName=CloudNap-Setup
  &param_ExternalId=1234-abcd-5678-efgh
